#!/bin/sh

cat /dev/null > logA
for size in 1000 10000 100000
do
	for order in random sorted reversed duplicate duplicateR duplicateS
	do
		echo === Testing for $order input, size $size === >> logA
		for i in 1 2 3 4 5
		do
			{ cat tests/$order$size | /usr/bin/time -f '%U' ./sortA > /dev/null ; } 2>> logA
		done
		echo "" >> logA
	done
done
